# Generated by Django 5.2.6 on 2025-09-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caravana', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('peso', models.FloatField()),
                ('sexo', models.CharField(max_length=20)),
                ('estado_reproductivo', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_productivo', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
