# Generated by Django 5.2.6 on 2025-10-20 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0002_movimientoeconomico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('prenez', models.CharField(choices=[('Preñada', 'Preñada'), ('Vacía', 'Vacía'), ('En duda', 'En duda')], max_length=20)),
                ('ovarios', models.CharField(choices=[('Sin alteraciones', 'Sin alteraciones'), ('Con alteraciones', 'Con alteraciones')], max_length=30)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animales.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('condicion', models.CharField(max_length=50)),
                ('medicacion', models.CharField(max_length=50)),
                ('dosis', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('realizado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animales.animal')),
            ],
        ),
    ]
