# Generated by Django 5.2.6 on 2025-10-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0003_tacto_tratamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='tipo_animal',
            field=models.CharField(choices=[('Vaca', 'Vaca'), ('Ternero', 'Ternero'), ('Novillo', 'Novillo')], default='Vaca', max_length=20),
        ),
    ]
