# Generated by Django 5.2.6 on 2025-10-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0004_animal_tipo_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='salida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
